name: ๐ ฺฏุฒุงุฑุด ูุดฺฉู
description: ูุทูุงู ูุง ุฑุง ุงุฒ ูุดฺฉู ฺฉู ุชุฌุฑุจู ฺฉุฑุฏูโุงุฏ ูุทูุน ฺฉูุฏ
title: "[ุจุงฺฏ]: "
labels: ["๐ bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ุงุฒ ุงูฺฉู ูุง ุฑุง ุฏุฑ ุฌุฑุงู ุงู ูุดฺฉู ูุฑุงุฑ ุฏุงุฏุฏ ุณูพุงุณฺฏุฒุงุฑู! ุงู ุงุทูุงุนุงุช ุจู ูุง ฺฉูฺฉ ูโฺฉูุฏ ุชุง ุณุฑุนโุชุฑ ุขู ุฑุง ุจุฑุทุฑู ฺฉูู.
  - type: dropdown
    id: os
    attributes:
      label: ุงุฒ ฺู ุณุณุชู ุงุณุชูุงุฏู ูโฺฉูุฏุ
      description: ุณุณุชูโุนุงูู ุฎูุฏ ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ
      options:
        - ุงูุจููุชู 22.04
        - ุงูุจููุชู 24.04
        - ุฏุจุงู 12
    validations:
      required: true
  - type: input
    id: hysteria2-version
    attributes:
      label: ุงุฒ ฺู ูุณุฎูโุง ุงุณุชูุงุฏู ูโฺฉูุฏุ
      description: ุดูุงุฑู ูุณุฎู Hysteria2 Panel 
      placeholder: "ูุซุงู: 1.2.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: ฺู ูุดฺฉู ุฑุฎ ุฏุงุฏู ุงุณุชุ
      description: ุชูุถุญ ุฏูุฏ ฺู ุงุชูุงู ุงูุชุงุฏู ู ฺฺฏููู ูโุชูุงู ุขู ุฑุง ุฏูุจุงุฑู ุงุฌุงุฏ ฺฉุฑุฏ
      placeholder: |
        ูุซุงู:
        1. ุฑู "ุงูุฒูุฏู ฺฉุงุฑุจุฑ" ฺฉูฺฉ ฺฉุฑุฏู
        2. ูุฑู ุฑุง ูพุฑ ฺฉุฑุฏู
        3. ููุช ุฑู ุฏฺฉูู ุฐุฎุฑู ฺฉูฺฉ ฺฉุฑุฏูุ ูพุงู ุฎุทุง ุฏุฑุงูุช ฺฉุฑุฏู
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: ุงุทูุงุนุงุช ููุฏ ุฏฺฏุฑุ
      description: ุชุตุงูุฑุ ูพุงูโูุง ุฎุทุง ุง ูุงฺฏโูุง ูโุชูุงููุฏ ุจุณุงุฑ ููุฏ ุจุงุดูุฏ (ุงุฎุชุงุฑ)
      placeholder: ูโุชูุงูุฏ ุงุณฺฉุฑูโุดุงุชโูุง ุฑุง ุงูุฌุง ูุฑุงุฑ ุฏูุฏ ุง ูพุงูโูุง ุฎุทุง ุฑุง ฺฉูพ ฺฉูุฏ
    validations:
      required: false
