CLI_PATH="/etc/hysteria/core/cli.py"
USERS_FILE="/etc/hysteria/users.json"
TRAFFIC_FILE="/etc/hysteria/traffic_data.json"
CONFIG_FILE="/etc/hysteria/config.json"
TELEGRAM_ENV="/etc/hysteria/core/scripts/telegrambot/.env"
SINGBOX_ENV="/etc/hysteria/core/scripts/singbox/.env"
